routes:
  /:
    template: home
  /atlas/:
    controller: channel
    filter: tag:technical-reports
    template: atlas

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
